url: https://y7kim.github.io
baseurl: 

# Site settings
title:  Ada Web Services
logo: Ada-logo.png
email: 
description: "Ada Web Services"
# Team names, titles and social links
people:
- name: 
  pic: 1
  position:
  
- name: 
  pic: 2
  position: 
  
- name: 
  pic: 3
  position: 
  
- name: 
  pic: 4
  position: 
 

- name: 
  pic: 5
  position: 

 

  

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/
  - title: facebook
    url: https://facebook.com/
  - title: instagram
  



# Postal address (add as many lines as necessary)
address:
  - line: 401, Aditya 
  - line: Mahakali Nagar
  - line: Mulund (East)
  - line: Mumbai 400081

# Build settings
markdown: kramdown
permalink: pretty
